### ISSUE TITLE
Feature Request:  Column Names provided in the dataset documentation

### ISSUE THREAD

**Issue by bms63** [pharmaverse/pharmaversesdtm#125]
### Feature Idea

Could we have a list of the columns available in the dataset?  I don't feel like loading them and doing colnames(data) cuz im lazy...
![image](https://github.com/user-attachments/assets/8fac6e70-58a9-4311-8e4d-b129fa2ae86d)

**Comment by manciniedoardo** [comment]
Will look into it for next release @bms63

**Comment by manciniedoardo** [comment]
Duplicate of #111
