### ISSUE TITLE
Creating ADDC code using admiral package macros

### ISSUE THREAD

**Issue by Sreeguna** [pharmaverse/pharmaversesdtm#19]
### Please select a category the issue is focused on?

I have a new documentation idea! Yay!

### Let us know where something needs a refresh or put your idea here!

I have some new idea of creating ADDC code using admiral package macro. But FAMH admiral SDTM dataset is not present which is required to create ADDC with admiral package macros. And also needed few oncology specific SDTM datasets in **admiral.test** package.

**Comment by manciniedoardo** [comment]
Hi @Sreeguna - we are actually in the process of reviewing and relaunching the contents of `{admiral.test}` in this new package, `{admiral.data}`, so i have transferred your issue here as it looks like you'll have to set up `FAMH` first!

**Comment by manciniedoardo** [comment]
@Sreeguna we are going to close this issue for now due to lack of activity, but please let us know in the future if you are ever interested in picking this back up.
