### ISSUE TITLE
General Issue: Move any test data in {admiralophtha} to {admiraldata}

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/pharmaversesdtm#2]
### Background Information

- Prefix: `admiralophtha_<dataset>`. 
- {admiralophtha} contact: Edoardo Mancini @manciniedoardo 

### Definition of Done

- SDTM contents of `data` folder of {admiralophtha}, as well as any relevant files in `dev` folder in copied over to same locations in {admiraldata}. 
- New datasets catalogued in `data.R`.

**Comment by kaz462** [comment]
@manciniedoardo could you help double check that the following files should be copied from {admiralophtha}? 

5 `.rda`, 5 programs
```
R
└── data.R       #5 datasets
data
├── admiralophtha_adbcva.rda
├── admiralophtha_adoe.rda
├── admiralophtha_advfq.rda
├── admiralophtha_ex.rda
└── admiralophtha_qs.rda
inst
└── templates
    ├── ad_adbcva.R              
    ├── ad_adoe.R
    └── ad_advfq.R
dev
├── ex.R
└── vfq.R
```

**Comment by kaz462** [comment]
only copy SDTM: ex.R, vfq.R
