### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/pharmaversesdtm#29]
should we remove `admiral_` prefix?

**Comment by kaz462** [comment]
remove admiral_

**Comment by kaz462** [comment]
@pharmaverse/admiraldata 
For datasets that are TA-specific, what do you think of using "domain_TA" (e.g., rs_onco) for naming instead of "TA_domain" (onco_rs)?

**Comment by manciniedoardo** [comment]
Happy to either way, will leave decision up to you.

**Comment by bundfussr** [comment]
I am happy with either way, too.

**Comment by bundfussr** [comment]
Where should additional fragments be placed? For example, should we use `rs_onco_irecist`, `rs_irecist_onco`, `onco_rs_irecist`, `onco_irecist_rs`, `irecist_onco_rs`, or something else?

**Comment by kaz462** [comment]
how about domain_TA_others (others go from broader categories to more specific ones)?

**Comment by bundfussr** [comment]
> how about domain_TA_others (others go from broader categories to more specific ones)?

Looks good to me.

**Comment by kaz462** [comment]
When do we need to add prefix `raw_`? The naming for `raw_ae` and `admiral_ae` in [admiral.test/data.R](https://github.com/pharmaverse/admiral.test/blob/main/R/data.R) makes sense to me, but `admiral_cm`/`admiral_dm` are directly from CDSIC pilot data, should we rename them to `raw_cm`/`raw_dm`? 

Can we have definition for those `raw_` datasets? e.g., directly from CDISC pilot data

**Comment by kaz462** [comment]
The following 31 datasets are from `admiral.test` data folder -

- 1st column: `admiral_eg` has no source indicated
- 2nd column: 14 datasets are directly from CDISC pilot data
     - rename them all to `raw_domain`? if agreed, update the last section of README.

- 3rd column:  6 datasets are updated based on CDISC pilot data. 
     - can we use the same program ( `dev/update_domain.R`) to update Existing SDTM Datasets in the future?
- 4th column: 10 datasets are generated from scratch by `dev/domain.R`
     - `tr`, `tu`, `rs` are obvisously oncology domains,  is it still necessary to add suffix? e.g., `rs_onco`



no   source/program | Raw (directly from CDISC pilot   data) | Updated from raw | Program |  
-- | -- | -- | -- | --
admiral_eg | raw_ae | admiral_ae | admiral_pc |  
  | raw_ds | admiral_ds | admiral_pp |  
  | raw_lb | admiral_lb | admiral_oe | (ophtha)
  | raw_mh | admiral_mh | admiral_sc | (ophtha)
  | raw_qs | admiral_qs | admiral_sdg_db |  
  | raw_suppds | admiral_suppds | admiral_smq_db |  
  | admiral_ex |   | admiral_tr | (onco)
  | admiral_suppae |   | admiral_supptr | (onco)
  | admiral_cm |   | admiral_tu | (onco)
  | admiral_sv |   | admiral_rs | (onco)
  | admiral_ts |   |   |  
  | admiral_vs |   |   |  
  | admiral_dm |   |   |  
  | admiral_suppdm |   |   |

**Comment by bundfussr** [comment]
Regarding the 2nd column I would prefer option 2 because for the user it does not matter if the dataset is copied directly from the CDISC pilot, the dataset is a modified CDISC pilot dataset, or a completely new generated dataset. I think for the users it is easier if the name does not depend on the source. It also avoids that the users need to update their code. For example, if we use `raw_dm` now and change it later to `dm` because we added something, all users which used `raw_dm` would need to update their code to use `dm`.

**Comment by manciniedoardo** [comment]
Agree with @bundfussr. I think the most futureproof strategy is to:

- name datasets copied directly from the CDISC pilot `raw_<datasetname>` eg `raw_dm`
- name the resulting test dataset that we produce `admiral_<domain>` (or whatever naming convention we choose) _even if we don't make any updates._ 

This way, we are more consistent with our naming approach, and also if we want to make updates in the future, we can just edit the file.

**Comment by kaz462** [comment]
Hi @sophie-gem , we noticed that you previously renamed the `admiral_eg` data, do you happen to know the source of this dataset? Thanks!

**Comment by sophie-gem** [comment]
Hi @kaz462, is this not the CDISC pilot EG dataset? I only ask as there is a template program in the `inst/templates/ad_adeg.R` that states:

![image](https://github.com/pharmaverse/pharmaversesdtm/assets/90790226/bbbc2844-a2ea-4af7-b385-d14bbabbb98e)

and then it goes on to load the `admiral_eg` dataset.

**Comment by sophie-gem** [comment]
If this is not the case - please let me know and I'll have another look

**Comment by kaz462** [comment]
Thanks @sophie-gem for checking! 

> Hi @kaz462, is this not the CDISC pilot EG dataset? I only ask as there is a template program in the `inst/templates/ad_adeg.R` that states:
>
I thought so too -  `STUDYID=CDISCPILOT01` in `eg`
![image](https://github.com/pharmaverse/pharmaversesdtm/assets/47867131/5034203e-bb71-4de2-b478-fb67047f8886)

But I couldn't find `eg` from [the CDISC pilot data](https://github.com/cdisc-org/sdtm-adam-pilot-project/tree/master/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm), is there another URL?

**Comment by kaz462** [comment]
Closing this issue for naming convention.
A separate issue created for `admiral_eg`: https://github.com/pharmaverse/pharmaversesdtm/issues/56
