### ISSUE TITLE
General Issue: Add test data for admiralonco iRecist

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/pharmaversesdtm#32]
### Background Information

Example data for the iRecist vignettes in admiralonco should be added: `rs_onco_irecist`.

**Comment by bundfussr** [comment]
You can easily create a `tribble()` call from the excel file by using the `datapasta` package. Copy a range of cells in the excel sheet and then call the "Paste as tribble" addin.
![image](https://github.com/pharmaverse/pharmaversesdtm/assets/80953585/035c9e1d-f535-4436-85b1-6b79ad196cec)

I would exclude columns with constant values from the `tribble()` call and add them via a `mutate()` call. This should reduce the length of the lines a bit.

**Comment by Thampi-hub** [comment]
I created the tribble in a R-script using the datapasta like you suggested _(not uploaded to Github yet)_. Do I store only this tribble R-script in the data folder? Also, wouldn't that be inconvenient to read the data afterwards? 

Alternatively I would suggest we create 2 files: the tribble R-script and its output saved as a rda-file. 
1. The **.rda data file** could be saved in data folder. 
2. The **tribble R-script** can be saved in the data-raw folder (or anywhere else), in case the values had to be modified later. 
Let me know your thoughts on this!

**Comment by bundfussr** [comment]
Please store the data file in the `data` folder and the R script in the `data-raw` folder.

The `data-raw` folder was already created in the `devel` branch but after you have created your feature branch. So you need to merge `devel` into your feature branch to get it.

The R script should be named as the dataset, i.e., `rs_onco_irecist.R`.

**Comment by Thampi-hub** [comment]
Raised a new pull request with both files (rs_onco_irecist.R and rs_onco_irecist.rda) included.

**Comment by bundfussr** [comment]
> @Thampi-hub @bundfussr are you planning to release it in Q4, 2023?

Yes, we need it for the next admiralonco release.
