### ISSUE TITLE
General Issue: Move any test data in {admiralvaccine} to {admiraldata}

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/pharmaversesdtm#4]
### Background Information

Prefix: `vaccine_<dataset>`.
{admiralvaccine} contact: Neetu Sangaru @neetusan .

### Definition of Done

- SDTM contents of  `data` folder of {admiralvaccine}, as well as any relevant files in `dev` folder in copied over to same locations in {pharmaversesdtm}.
- New datasets catalogued in `data.R`.

**Comment by manciniedoardo** [comment]
For this one, may have to wait until first release of {admiralvaccine}.

**Comment by kaz462** [comment]
should we wait until the following issue is resolved?
https://github.com/pharmaverse/admiralvaccine/issues/218

**Comment by manciniedoardo** [comment]
@ahasoplakus do you have bandwidth to cover this, please?

**Comment by ahasoplakus** [comment]
> @ahasoplakus do you have bandwidth to cover this, please?

Hi @manciniedoardo Please review the PR linked with this issue https://github.com/pharmaverse/pharmaversesdtm/pull/74
