### ISSUE TITLE
Evaluate downstream impact for those depend on `admiral.test`

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/pharmaversesdtm#44]
### Background Information

After moving data from `admiral.test` to `pharmaversesdtm`, we used the new naming convention and updated some programs (e.g., added `set.seed` in `pc.R/qs_ophtha.R`)

### Definition of Done

Check and update `admiral/admialonco/admiralophtha/admiralvaccine`
1. replace `admiral.test` by `pharmaversesdtm` 
2. update dataset name accordingly
3. check if everything runs fine

**Comment by kaz462** [comment]
SDTM data from {admiral.test} {admiralophtha} is ready in {pharmaversesdtm}
- Issue created for {admiral}: https://github.com/pharmaverse/admiral/issues/2040 

- @manciniedoardo could you please check if any updates are needed for {admiralophtha}?

**Comment by manciniedoardo** [comment]
See [here](https://github.com/pharmaverse/admiralophtha/issues/184)

**Comment by kaz462** [comment]
Hi @neetusan @bundfussr, could you kindly check for `admiralvaccine` and `admialonco`? - Migration from `admiral.test` to `pharmaversesdtm` needs to be done in the upcoming release. Thank you!
