### ISSUE TITLE
 update badges for `pharmaversesdtm`

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/pharmaversesdtm#62]
@pharmaverse/admiraldata any idea how to add badges for `pharmaversesdtm` - http://pharmaverse.org/shields/admiral.svg?
[<img src="http://pharmaverse.org/shields/admiral.svg"/>](https://pharmaverse.org)

Since test coverage will be 0, should we remove it?
[![Test Coverage](https://raw.githubusercontent.com/pharmaverse/pharmaversesdtm/badges/main/test-coverage.svg)](https://github.com/pharmaverse/pharmaversesdtm/actions/workflows/code-coverage.yml)

_Originally posted by @kaz462 in https://github.com/pharmaverse/pharmaversesdtm/issues/60#issuecomment-1697627530_

**Comment by bundfussr** [comment]
As it is a data package and we do not export any functions, I would remove the test coverage badge.
