### ISSUE TITLE
Documentation:  Standardize description text in reference page

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/pharmaversesdtm#83]
### Let us know where something needs a refresh or put your idea here!

Currently, the descrioption text for datasets in the reference page is not always of the same structure. Can we agree on a convention and stick to it across all datasets (TA specific and not)?
![image](https://github.com/pharmaverse/pharmaversesdtm/assets/53403957/eb52438d-b784-4091-b4b8-76b791fe53b1)

**Comment by manciniedoardo** [comment]
@sadchla-codes could we also change the page title from Function Reference to  Dataset Reference please?

**Comment by manciniedoardo** [comment]
I'm also noticing something fishy going on here... 
![image](https://github.com/pharmaverse/pharmaversesdtm/assets/53403957/18ade2f1-d9ce-4026-bc85-4ca8e6d879df)

**Comment by sadchla-codes** [comment]
> I'm also noticing something fishy going on here... ![image](https://private-user-images.githubusercontent.com/53403957/331268567-18ade2f1-d9ce-4026-bc85-4ca8e6d879df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzQ4MDksIm5iZiI6MTcxNTg3NDUwOSwicGF0aCI6Ii81MzQwMzk1Ny8zMzEyNjg1NjctMThhZGUyZjEtZDljZS00MDI2LWJjODUtNGNhOGU2ZDg3OWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE1NDgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MDBkMjc1NjdkYTBkYTA0MTBjYjcwNWYxNDAwNGY2OGUzNGUwYTg4MDc0ZjNkZmM4NWZjZDIxNjg3NDNmYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i12E4jmeMe6M1eUpvPiIX4QVYrUcC6_RWz3rLIk6FE0)


I will look into them @manciniedoardo
