### ISSUE TITLE
Bug: Duplicates in `SV`

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/pharmaversesdtm#85]
### What happened?

There are duplicate observations in `SV`:
```
Duplicate records with respect to `USUBJID` and `VISIT`.
# A tibble: 2 × 8
  USUBJID     VISIT           STUDYID      DOMAIN VISITNUM VISITDY SVSTDTC    SVENDTC   
* <chr>       <chr>           <chr>        <chr>     <dbl>   <dbl> <chr>      <chr>     
1 01-711-1143 UNSCHEDULED 9.2 CDISCPILOT01 SV          9.2      NA 2013-06-22 2013-06-22
2 01-711-1143 UNSCHEDULED 9.2 CDISCPILOT01 SV          9.2      NA 2013-09-22 2013-09-22
```
This causes invalid observations in `RS` (`RSSTRESC = "CHECK"`).

**Comment by PoojaKumari05** [comment]
Hi @bundfussr for this issue the SVSTDTC & SVENDTC are different for the 2 rows mentioned in screenshot, do we want to amend the first row as VISIT = UNSCHEDULED 9.1? Please suggest.

**Comment by bundfussr** [comment]
Hi @PoojaKumari05 , sorry, the issue description is not clear.

Yes, I would suggest to set `VISIT = "UNSCHEDULED 9.1"` and `VISITNUM = 9.1` for the first row.

**Comment by PoojaKumari05** [comment]
> Hi @PoojaKumari05 , sorry, the issue description is not clear.
> 
> Yes, I would suggest to set `VISIT = "UNSCHEDULED 9.1"` and `VISITNUM = 9.1` for the first row.

Thanks @bundfussr for clarifying! :)
