### ISSUE TITLE
Feature Request: Create RS using IMWG criteria

### ISSUE THREAD

**Issue by bundfussr** [pharmaverse/pharmaversesdtm#86]
### Feature Idea

Create RS using IMWG criteria

**Comment by manciniedoardo** [comment]
@bundfussr @amitjaingsk @vinhn23 just checking we are on track for this by end of next week?

**Comment by bundfussr** [comment]
> @bundfussr @amitjaingsk @vinhn23 just checking we are on track for this by end of next week?

Yes, that should work.
