### ISSUE TITLE
Feature Request:  Add/Update SDTM test data for {admiralpeds}

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/pharmaversesdtm#88]
### Feature Idea

Add/Update SDTM test data for {admiralpeds}

### Relevant Input

N/A

### Relevant Output

N/A

### Reproducible Example/Pseudo Code

N/A

**Comment by manciniedoardo** [comment]
@rossfarrugia we would like to release pharmaversesdtm 1.0 at the start of June. Will the test data be ready by then? Otherwise would need to add in a later release and temporarily keep in admiralpeds.

**Comment by rossfarrugia** [comment]
@manciniedoardo - @kabis-ops has created this at https://github.com/pharmaverse/admiralpeds/tree/main/data - see `dm_peds` and `vs_peds`, and programs at https://github.com/pharmaverse/admiralpeds/tree/main/data-raw. But I just quickly looked and this hasn't been created as an extension of the CDISC pilot study data so wouldn't be fit to go in pharmaversesdtm yet without some re-work. e.g. new subject IDs have been created as `"PEDS-1001"` for example rather than building on those dummy subjects in pharmaversesdtm `DM`. I would go ahead with your planned release for June and assume that we'd move these over later.

**Comment by manciniedoardo** [comment]
Thanks @rossfarrugia - I will label this issue as Post 1.0. Perhaps it would be good then to also make a companion issue (and link to this one) on the admiralpeds side for when you do have a chance to move the data over.

**Comment by rossfarrugia** [comment]
yes we have it here https://github.com/pharmaverse/admiralpeds/issues/36, will let you know if anything changes. We might be able to squeeze it in earlier as its impacting our template/vignette anyway as we don't have an `ADSL` matching these patients as they are now.

**Comment by kaz462** [comment]
> I think this one can stay open for now and we'll move these datasets over after we do admiralpeds 0.1.0 release in July. It corresponds now to this issue [pharmaverse/admiralpeds#40](https://github.com/pharmaverse/admiralpeds/issues/40)

Thanks for re-opening. It was linked to the wrong PR and got closed when that PR was merged, all good now.
